FROM golang:1.12 AS build-image

WORKDIR /work
ADD main.go main.go
RUN go build -ldflags '-s -w' -o /bin/hello

FROM ubuntu:14.04
COPY --from=build-image /bin/hello /bin/hello

ENTRYPOINT ["/bin/hello"]
